"""add <erp_export> table

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-01 11:08:31.434549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_export',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ordre_id', sa.Integer(), nullable=False),
    sa.Column('produit_ref', sa.String(length=20), nullable=False),
    sa.Column('site', sa.String(length=50), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('date_lancement', sa.DateTime(), nullable=False),
    sa.Column('date_fin_prevue', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('ouvrier_id', sa.String(length=64), nullable=False),
    sa.Column('quantite_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['produit_ref'], ['produits.produit_ref'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_export_ordre_id'), 'erp_export', ['ordre_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_erp_export_ordre_id'), table_name='erp_export')
    op.drop_table('erp_export')
    # ### end Alembic commands ###
